class ListDataModel {
  static Map<String, String> scripCompanyNameData = {
    "NMBD2085": "10 % NMB DEBENTURE 2085",
    "HBLD83": "10% Himalayan Bank Debenture 2083",
    "LBLD86": "10% Laxmi Bank Debenture 2086",
    "NBLD82": "10% Nabil Debenture 2082",
    "SBIBD86": "10% Nepal SBI Bank Debenture 2086",
    "NICAD 85/86": "10% NIC Asia Debenture 2085/86",
    "PBLD84": "10% Prabhu Bank Debenture 2084",
    "SAND2085": "10% Sanima Bank Limited Debenture",
    "SRD80": "10% Sunrise Debenture 2080",
    "CIZBD86": "10.25% Citizens Bank Debenture 2086",
    "GBD80/81": "10.25% GLOBAL IME BANK LTD. DEBENTURE 2080/81",
    "KBLD86": "10.25% KBL Debenture 2086",
    "MBLD2085": "10.25% Machhapuchhre Bank Debenture 2085",
    "NBBD2085": "10.25% NBBL Debenture 2085",
    "NICD83/84": "10.25% NIC Asia Debenture 2083/84",
    "PBLD86": "10.25% Prabhu Bank Debenture 2086",
    "SBLD83": "10.25% SBL Debenture 2083",
    "SRBLD83": "10.25% Sunrise Bank Debenture 2083",
    "ADBLD83": "10.35% Agricultural Bank Debenture 2083",
    "NIBD2082": "10.5 % NEPAL INVESTMENT DEBENTURE 2082",
    "SBLD2082": "10.50% SBL Debenture 2082",
    "NICAD8283": "11% NIC Asia Debenture 082/83",
    "GWFD83": "12 % Goodwill Finance Limited Debenture 2083",
    "ICFCD83": "12% ICFC Finance Limited Debenture 2083",
    "BOKD2079": "8% BOK Debenture 2079",
    "EBLD2078": "8% EBL Debenture 2078",
    "NIBD84": "8.5% Nepal Investment Bank Debenture 2084",
    "SBD87": "8.5% Sanima Debenture 2087",
    "SBLD84": "8.5% SBL Debenture 2084",
    "NICAD8182": "9% NIC Asia Debenture 2081/82",
    "MFLD85": "9.5% Manjushree Finance Limited Debenture 2085",
    "NCCD86": "9.5% NCC Debenture 2086",
    "ACLBSL": "Aarambha Chautari Laghubitta Bittiya Sanstha Limited",
    "AKBSL": "ADHIKHOLA LAGHUBITTA BITTIYA SANSTHA LIMITED",
    "ADBL": "Agriculture Development Bank Limited",
    "AIL": "Ajod Insurance Limited",
    "AKJCL": "Ankhu Khola Jalvidhyut Company Ltd",
    "API": "Api Power Company Ltd.",
    "AMFI": "Arambha Microfinance Bittiya Sanstha Ltd.",
    "AKPL": "Arun Kabeli Power Ltd.",
    "AHPC": "Arun Valley Hydropower Development Co. Ltd.",
    "AVU": "Arun Vanaspati Udhyog Limited",
    "ALBSL": "Asha Laghubitta Bittiya Sanstha Ltd",
    "ALICL": "Asian Life Insurance Co. Limited",
    "BOKL": "Bank of Kathmandu Ltd.",
    "BARUN": "Barun Hydropower Co. Ltd.",
    "BFC": "Best Finance Company Ltd.",
    "BHBL": "Bhargav Bikash Bank Ltd.",
    "BSL": "Birat Shoe Limited",
    "BBC": "Bishal Bazar Company Limited",
    "BNL": "Bottlers Nepal (Balaju) Limited",
    "BNT": "Bottlers Nepal (Terai) Limited",
    "BPCL": "Butwal Power Company Limited",
    "BSM": "Butwal Spinning Mills Limited",
    "CMB": "Capital Merchant Bank & Finance Co. Ltd.",
    "CHDC": "CEDB Hydropower Development Company Limited",
    "CFCL": "Central Finance Co. Ltd.",
    "CCBL": "Century Commercial Bank Ltd.",
    "CBBL": "Chhimek Laghubitta Bikas Bank Limited",
    "CHL": "Chhyangdi Hydropower Ltd.",
    "CHCL": "Chilime Hydropower Company Limited",
    "CZBIL": "Citizen Bank International Limited",
    "CIT": "Citizen Investment Trust",
    "CMF1": "Citizens Mutual Fund -1",
    "CMF2": "CITIZENS MUTUAL FUND 2",
    "CEFL": "City Express Finance Co. Limited",
    "CBL": "Civil Bank Ltd",
    "CLBSL": "Civil Laghubitta Bittiya Sanstha Ltd.",
    "CORBL": "Corporate Development Bank Limited",
    "CFL": "Crystal Finance Ltd.",
    "DDBL": "Deprosc Laghubitta Bittiya Sanstha Limited",
    "DHPL": "Dibyashwori Hydropower Ltd.",
    "EBL": "Everest Bank Limited",
    "EBLCP": "Everest Bank Limited Con. Pref.",
    "EIC": "Everest Insurance Co. Ltd.",
    "EDBL": "Excel Development Bank Ltd.",
    "FMDBL": "First Micro Finance Development Bank Ltd.",
    "FHL": "Fleur Himalayan Limited",
    "FOWAD": "Forward Community Microfinance Bittiya Sanstha Ltd.",
    "GMFBS": "Ganapati Microfinance Bittiya Sanstha Limited",
    "GDBL": "Gandaki Bikas Bank Limited",
    "GBBL": "Garima Bikas Bank Limited",
    "GIC": "General Insurance Company Nepal Ltd",
    "GHL": "Ghalemdi Hydro Limited",
    "GGBSL": "Ghodighoda Laghubitta Bittiya Sanstha Ltd.",
    "GBIME": "Global IME Bank Limited",
    "GILB": "Global IME Laghubitta Bittiya Sanstha Ltd.",
    "GIMES1": "Global IME Samunnat Scheme-1",
    "GFCL": "Goodwill Finance Co. Ltd.",
    "GRU": "Gorakhkali Rubber Udhyog Limited",
    "GBLBS": "Grameen Bikas Laghubitta Bittiya Sanstha Ltd.",
    "GRDBL": "Green Development Bank Ltd.",
    "GLH": "GreenLife Hydropower Limited",
    "GMFIL": "Guheshowori Merchant Bank & Finance Co. Ltd.",
    "GLBSL": "Gurans Laghubitta Bittiya Sanstha Limited",
    "GLICL": "Gurans Life Insurance Company Ltd.",
    "GUFL": "Gurkhas Finance Ltd.",
    "HAMRO": "Hamro Bikas Bank Ltd.",
    "HBT": "Harisiddhi Brick And Tiles Limited",
    "HATH": "Hathway Finance Company Limited",
    "HDHPC": "Himal Dolakha Hydropower Company Limited",
    "HURJA": "Himalaya Urja Bikas Company Limited",
    "HBL": "Himalayan Bank Limited",
    "HDL": "Himalayan Distillery Limited",
    "HFL": "Himalayan Finance Limited (Bittiya Sanstha)",
    "HGI": "Himalayan General Insurance Co. Ltd",
    "HPPL": "Himalayan Power Partner Ltd.",
    "HIDCL": "Hydorelectricity Investment and Development Company Ltd",
    "ICFC": "ICFC Finance Limited",
    "IGI": "IME General Insurance Ltd.",
    "ILBS": "Infinity Laghubitta Bittiya Sanstha Limited",
    "JFL": "Janaki Finance Ltd.",
    "JBNL": "Janata Bank Nepal Ltd.",
    "JSLBB": "Janautthan Samudayic Laghubitta Bikas Bank Ltd.",
    "JOSHI": "Joshi Hydropower Development Company Ltd",
    "JBBL": "Jyoti Bikas Bank Limited",
    "JLI": "Jyoti Life Insurance Ltd",
    "JSM": "Jyoti Sinning Mills Limited",
    "KMCDB": "Kalika Microcredit Development Bank Ltd.",
    "KPCL": "Kalika power Company Ltd",
    "KSBBL": "Kamana Sewa Bikas Bank Limited",
    "KNBL": "Kankai Bikas Bank Ltd.",
    "KRBL": "Karnali Development Bank Limited",
    "KKHC": "Khanikhola Hydropower Co. Ltd.",
    "KLBSL": "Kisan Lagubitta Bittiya Sanstha Limited",
    "KBL": "Kumari Bank Limited",
    "KEF": "Kumari Equity Fund",
    "LFC": "Lalitpur Finance Ltd.",
    "LBL": "Laxmi Bank Limited",
    "LEMF": "Laxmi Equity Fund",
    "LLBS": "Laxmi Laghubitta Bittiya Sanstha Ltd.",
    "LUK": "Laxmi Unnati Kosh",
    "LEC": "Liberty Energy Company Limited",
    "LICN": "Life Insurance Co. Nepal",
    "LBBL": "Lumbini Bikas Bank Ltd.",
    "LGIL": "Lumbini General Insurance Co. Ltd.",
    "MBL": "Machhapuchhre Bank Limited",
    "MLBL": "Mahalaxmi Bikas Bank Ltd.",
    "MLBSL": "Mahila Lagubitta Bittiya Sanstha Limited",
    "MSMBS": "Mahila Sahayatra Microfinance Bittiya Sanstha Ltd.",
    "MSLB": "Mahuli Samudayik Laghubitta Bittiya Sanstha Ltd.",
    "MFIL": "Manjushree Finance Ltd.",
    "MEGA": "Mega Bank Nepal Ltd.",
    "MERO": "Mero Microfinance Bittiya Sanstha Ltd.",
    "MMFDB": "Mirmire Microfinance Development Bank Ltd.",
    "MDB": "Miteri Development Bank Limited",
    "MLBBL": "Mithila LaghuBitta Bittiya Sanstha Limited",
    "MEN": "Mountain Energy Nepal Limited",
    "MHNL": "Mountain Hydro Nepal Limited",
    "MNBBL": "Muktinath Bikas Bank Ltd.",
    "MPFL": "Multipurpose Finance Company Limited",
    "NBF2": "NABIL BALANCED FUND-2",
    "NABIL": "Nabil Bank Limited",
    "NEF": "Nabil Equity Fund",
    "NADEP": "Nadep Laghubittiya bittya Sanstha Ltd.",
    "NABBC": "Narayani Development Bank Limited",
    "NHPC": "National Hydro Power Company Limited",
    "NLICL": "National Life Insurance Co. Ltd.",
    "NMFBS": "National Microfinance Bittiya Sanstha Ltd.",
    "NIL": "Neco Insurance Co. Ltd.",
    "NAGRO": "Nepal Agro Laghubitta Bittiya Sanstha Limited",
    "NBB": "Nepal Bangladesh Bank Limited",
    "NBL": "Nepal Bank Limited",
    "NBBU": "Nepal Bitumin And Barrel Udhyog Limited",
    "NCCB": "Nepal Credit And Commercial Bank Limited",
    "NTC": "Nepal Doorsanchar Comapany Limited",
    "NFD": "Nepal Film Development Company Limited",
    "NFS": "Nepal Finance Ltd.",
    "NHDL": "Nepal Hydro Developers Ltd.",
    "NIFRA": "Nepal Infrastructure Bank Limited",
    "NICL": "Nepal Insurance Co. Ltd.",
    "NIB": "Nepal Investment Bank Limited",
    "NKU": "Nepal Khadya Udhyog Limited",
    "NLIC": "Nepal Life Insurance Co. Ltd.",
    "NLO": "Nepal Lube Oil Limited",
    "NRIC": "Nepal Reinsurance Company Limited",
    "SBI": "Nepal SBI Bank Limited",
    "NSEWA": "Nepal Seva Laghubitta Bittiya Sanstha Ltd.",
    "NSM": "Nepal Share Markets Ltd.",
    "NTL": "Nepal Tading Limited",
    "NVG": "Nepal Vanaspati Ghee Udhyog Limited",
    "NWC": "Nepal Welfare Company Limited",
    "NLBBL": "Nerude Laghubita Bikas Bank Limited",
    "NGPL": "Ngadi Group Power Ltd.",
    "NIBLPF": "NIBL Pragati Fund",
    "NIBSF1": "NIBL Samriddhi Fund 1",
    "NICBF": "NIC Asia Balanced Fund",
    "NICA": "NIC Asia Bank Ltd.",
    "NICGF": "NIC Asia Growth Fund",
    "NICLBSL": "NIC ASIA Laghubitta Bittiya Sanstha Limited",
    "NIDC": "NIDC Development Bank Ltd.",
    "NUBL": "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited",
    "NLG": "NLG Insurance Company Ltd.",
    "NMBMF": "NMB Microfinance Bittiya Sanstha Ltd.",
    "NMB50": "NMB 50",
    "NMB": "NMB Bank Limited",
    "NMBHF1": "NMB Hybrid Fund L-1",
    "NRN": "NRN Infrastructure and Development Limited",
    "ODBL": "Om Development Bank Ltd.",
    "PMHPL": "Panchakanya Mai Hydropower Ltd",
    "PPCL": "Panchthar Power Compant Limited",
    "PFL": "Pokhara Finance Ltd.",
    "PRVU": "Prabhu Bank Limited",
    "PRIN": "Prabhu Insurance Ltd.",
    "PLI": "Prabhu Life Insurance Limited",
    "PIC": "Premier Insurance Co. Ltd.",
    "PCBL": "Prime Commercial Bank Ltd.",
    "PLIC": "Prime Life Insurance Company Limited",
    "PROFL": "ProgressiveFinance Limited",
    "PICL": "Prudential Insurance Co. Ltd.",
    "RADHI": "Radhi Bidyut Company Ltd",
    "RJM": "Raghupati Jute Mills Limited",
    "RRHP": "Rairang Hydropower Development Company Ltd.",
    "RBCL": "Rastriya Beema Company Limited",
    "RHPL": "RASUWAGADHI HYDROPOWER COMPANY LIMITED",
    "RLFL": "Reliance Finance Ltd.",
    "RLI": "Reliance Life Insurance Limited",
    "RHPC": "Ridi Hydropower Development Company Ltd.",
    "RMDC": "RMDC Laghubitta Bittiya Sanstha Ltd.",
    "RSDC": "RSDC Laghubitta Bittiya Sanstha Ltd.",
    "RURU": "Ru Ru Jalbidhyut Pariyojana Limited",
    "SABSL": "SABAIKO LAGHUBITTA BITTIYA SANSTHA LIMITED",
    "SDLBSL": "Sadhana Laghubitta Bittiya Sanstha Limited",
    "SIC": "Sagarmatha Insurance Co. Ltd.",
    "SHBL": "Sahara Bikas Bank Ltd.",
    "SBBLJ": "Sahayogi Bikas Bank Limited",
    "STC": "Salt Trading Corporation",
    "SMATA": "Samata Gharelu Laghubitta Bittiya Sanstha Limited",
    "SFC": "Samjhana Finance Co. Ltd.",
    "SFCL": "Samriddhi Finance Company Limited",
    "SLBSL": "Samudayik Laghubitta Bittiya Sanstha Limited",
    "SKBBL": "Sana Kisan Bikas Bank Ltd",
    "SANIMA": "Sanima Bank Limited",
    "SAEF": "Sanima Equity Fund",
    "SGI": "Sanima General Insurance Limited",
    "SLCF": "Sanima Large Cap Fund",
    "SHPC": "Sanima Mai Hydropower Ltd.",
    "SJCL": "SANJEN JALAVIDHYUT COMPANY LIMITED",
    "SAPDBL": "Saptakoshi Development Bank Ltd",
    "SNLB": "Sarathi Nepal Laghubitta Bittiya Sanstha Limited",
    "SADBL": "Shangrila Development Bank Ltd.",
    "SICL": "Shikhar Insurance Co. Ltd.",
    "SHINE": "Shine Resunga Development Bank Ltd.",
    "SSHL": "Shiva Shree Hydropower Ltd",
    "SHIVM": "SHIVAM CEMENTS LTD",
    "SBPP": "Shree Bhrikuti Pulp And Paper Limited",
    "SIFC": "Shree Investment Finance Co. Ltd.",
    "SRS": "Shree Ram Sugar Mills Limited",
    "SFFIL": "Shrijana Finance (Bittaya Sanstha)",
    "SBL": "Siddhartha Bank Limited",
    "SEF": "Siddhartha Equity Fund",
    "SEOS": "Siddhartha Equity Orineted Scheme",
    "SIL": "	Siddhartha Insurance Ltd.",
    "SIGS2": "Siddhartha Investment Growth Scheme - 2",
    "SINDU": "Sindhu Bikash Bank Ltd",
    "SHEL": "Singati Hydro Energy Limited",
    "SPARS": "Sparsha Laghubitta Bittiya Sanstha Limited",
    "SCB": "Standard Chartered Bank Limited",
    "SMFDB": "Summit Laghubitta Bittiya Sanstha Limited",
    "SRBL": "Sunrise Bank Limited",
    "SBCF": "Sunrise Bluechip Fund",
    "SFMF": "Sunrise First Mutual Fund",
    "SMB": "Support Microfinance Bittiya Sanstha Ltd.",
    "SLICL": "Surya Life Insurance Company Limited",
    "SLBS": "Suryodaya Laghubitta Bittiya Sanstha Ltd.",
    "SWBBL": "Swabalamban Laghubitta Bittiya Sanstha Limited",
    "SMFBS": "Swabhimaan Laghubitta Bittiya Sanstha Limited",
    "SDESI": "Swadeshi Laghubitta Bittiya Sanstha Ltd.",
    "SLBBL": "Swarojgar Laghu Bitta Bikas Bank Ltd.",
    "SYFL": "Synergy Finance Ltd.",
    "SPDL": "Synergy Power Development Ltd.",
    "TRH": "Taragaon Regency Hotel Limited",
    "TRHPR": "Taragaon Regency Hotels Ltd. Preference Share",
    "TMDBL": "Tinau Mission Development Bank Limited",
    "UNL": "Unilever Nepal Limited",
    "UNHPL": "Union Hydropower Limited",
    "UFL": "United Finance Ltd.",
    "UMRH": "United IDI Mardi RB Hydropower Limited.",
    "UIC": "United Insurance Co. (Nepal) Ltd.",
    "UMHL": "United Modi Hydropower Ltd.",
    "UPCL": "UNIVERSAL POWER COMPANY LTD",
    "USLB": "Unnati Sahakarya Laghubitta Bittiya Sanstha Limited",
    "UPPER": "Upper Tamakoshi Hydropower Ltd",
    "VLBS": "Vijaya laghubitta Bittiya Sanstha Ltd.",
    "WOMI": "Womi Microfinance Bittiya Sanstha Ltd.",
    "YHL": "Yak And Yeti Hotel Limited",
  };

  static Map<String, String> companySectorData = {
    "10 % NMB DEBENTURE 2085": "Corporate Debenture",
    "10% Himalayan Bank Debenture 2083": "Corporate Debenture",
    "10% Laxmi Bank Debenture 2086": "Corporate Debenture",
    "10% Nabil Debenture 2082": "Corporate Debenture",
    "10% Nepal SBI Bank Debenture 2086": "Corporate Debenture",
    "10% NIC Asia Debenture 2085/86": "Corporate Debenture",
    "10% Prabhu Bank Debenture 2084": "Corporate Debenture",
    "10% Sanima Bank Limited Debenture": "Corporate Debenture",
    "10% Sunrise Debenture 2080": "Corporate Debenture",
    "10.25% Citizens Bank Debenture 2086": "Corporate Debenture",
    "10.25% GLOBAL IME BANK LTD. DEBENTURE 2080/81": "Corporate Debenture",
    "10.25% KBL Debenture 2086": "Corporate Debenture",
    "10.25% Machhapuchhre Bank Debenture 2085": "Corporate Debenture",
    "10.25% NBBL Debenture 2085": "Corporate Debenture",
    "10.25% NIC Asia Debenture 2083/84": "Corporate Debenture",
    "10.25% Prabhu Bank Debenture 2086": "Corporate Debenture",
    "10.25% SBL Debenture 2083": "Corporate Debenture",
    "10.25% Sunrise Bank Debenture 2083": "Corporate Debenture",
    "10.35% Agricultural Bank Debenture 2083": "Corporate Debenture",
    "10.5 % NEPAL INVESTMENT DEBENTURE 2082": "Corporate Debenture",
    "10.50% SBL Debenture 2082": "Corporate Debenture",
    "11% NIC Asia Debenture 082/83": "Corporate Debenture",
    "12 % Goodwill Finance Limited Debenture 2083": "Corporate Debenture",
    "12% ICFC Finance Limited Debenture 2083": "Corporate Debenture",
    "8% BOK Debenture 2079": "Corporate Debenture",
    "8% EBL Debenture 2078": "Corporate Debenture",
    "8.5% Nepal Investment Bank Debenture 2084": "Corporate Debenture",
    "8.5% Sanima Debenture 2087": "Corporate Debenture",
    "8.5% SBL Debenture 2084": "Corporate Debenture",
    "9% NIC Asia Debenture 2081/82": "Corporate Debenture",
    "9.5% Manjushree Finance Limited Debenture 2085": "Corporate Debenture",
    "9.5% NCC Debenture 2086": "Corporate Debenture",
    "Aarambha Chautari Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "ADHIKHOLA LAGHUBITTA BITTIYA SANSTHA LIMITED": "Microfinance",
    "Agriculture Development Bank Limited": "Commercial Banks",
    "Ajod Insurance Limited": "Non Life Insurance",
    "Ankhu Khola Jalvidhyut Company Ltd": "Hydro Power",
    "Api Power Company Ltd.": "Hydro Power",
    "Arambha Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Arun Kabeli Power Ltd.": "Hydro Power",
    "Arun Valley Hydropower Development Co. Ltd.": "Hydro Power",
    "Arun Vanaspati Udhyog Limited": "Manufacturing And Processing",
    "Asha Laghubitta Bittiya Sanstha Ltd": "Microfinance",
    "Asian Life Insurance Co. Limited": "	Life Insurance",
    "Bank of Kathmandu Ltd.": "Commercial Banks",
    "Barun Hydropower Co. Ltd.": "Hydro Power",
    "Best Finance Company Ltd.": "Finance",
    "Bhargav Bikash Bank Ltd.": "Development Banks",
    "Birat Shoe Limited": "Manufacturing And Processing",
    "Bishal Bazar Company Limited": "Tradings",
    "Bottlers Nepal (Balaju) Limited": "Manufacturing And Processing",
    "Bottlers Nepal (Terai) Limited": "Manufacturing And Processing",
    "Butwal Power Company Limited": "Hydro Power",
    "Butwal Spinning Mills Limited": "Manufacturing And Processing",
    "Capital Merchant Bank & Finance Co. Ltd.": "Finance",
    "CEDB Hydropower Development Company Limited": "Investment",
    "Central Finance Co. Ltd.": "Finance",
    "Century Commercial Bank Ltd.": "Commercial Banks",
    "Chhimek Laghubitta Bikas Bank Limited": "Microfinance",
    "Chhyangdi Hydropower Ltd.": "Hydro Power",
    "Chilime Hydropower Company Limited": "Hydro Power",
    "Citizen Bank International Limited": "Commercial Banks",
    "Citizen Investment Trust": "Investment",
    "Citizens Mutual Fund -1": "Mutual Fund",
    "CITIZENS MUTUAL FUND 2": "Mutual Fund",
    "City Express Finance Co. Limited": "Finance",
    "Civil Bank Ltd": "Commercial Banks",
    "Civil Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Corporate Development Bank Limited": "Development Banks",
    "Crystal Finance Ltd.": "Finance",
    "Deprosc Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Dibyashwori Hydropower Ltd.": "Hydro Power",
    "Everest Bank Limited": "Commercial Banks",
    "Everest Bank Limited Con. Pref.": "Preferred Stock",
    "Everest Insurance Co. Ltd.": "Non Life Insurance",
    "Excel Development Bank Ltd.": "Development Banks",
    "First Micro Finance Development Bank Ltd.": "Microfinance",
    "Fleur Himalayan Limited": "Manufacturing And Processing",
    "Forward Community Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Ganapati Microfinance Bittiya Sanstha Limited": "Microfinance",
    "Gandaki Bikas Bank Limited": "Development Banks",
    "Garima Bikas Bank Limited": "Development Banks",
    "General Insurance Company Nepal Ltd": "Non Life Insurance",
    "Ghalemdi Hydro Limited": "Hydro Power",
    "Ghodighoda Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Global IME Bank Limited": "Commercial Banks",
    "Global IME Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Global IME Samunnat Scheme-1": "Mutual Fund",
    "Goodwill Finance Co. Ltd.": "Finance",
    "Gorakhkali Rubber Udhyog Limited": "Manufacturing And Processing",
    "Grameen Bikas Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Green Development Bank Ltd.": "Development Banks",
    "GreenLife Hydropower Limited": "Finance",
    "Guheshowori Merchant Bank & Finance Co. Ltd.": "Finance",
    "Gurans Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Gurans Life Insurance Company Ltd.": "Life Insurance",
    "Gurkhas Finance Ltd.": "Finance",
    "Hamro Bikas Bank Ltd.": "Development Banks",
    "Harisiddhi Brick And Tiles Limited": "Manufacturing And Processing",
    "Hathway Finance Company Limited": "Finance",
    "Himal Dolakha Hydropower Company Limited": "Hydro Power",
    "Himalaya Urja Bikas Company Limited": "Hydro Power",
    "Himalayan Bank Limited": "Commercial Banks",
    "Himalayan Distillery Limited": "Manufacturing And Processing",
    "Himalayan Finance Limited (Bittiya Sanstha)": "Finance",
    "Himalayan General Insurance Co. Ltd": "Non Life Insurance",
    "Himalayan Power Partner Ltd.": "Hydro Power",
    "Hydorelectricity Investment and Development Company Ltd": "Investment",
    "ICFC Finance Limited": "Finance",
    "IME General Insurance Ltd.": "Non Life Insurance",
    "Infinity Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Janaki Finance Ltd.": "Finance",
    "Janata Bank Nepal Ltd.": "Commercial Banks",
    "Janautthan Samudayic Laghubitta Bikas Bank Ltd.": "Microfinance",
    "Joshi Hydropower Development Company Ltd": "Hydro Power",
    "Jyoti Bikas Bank Limited": "Development Banks",
    "Jyoti Life Insurance Ltd": "Life Insurance",
    "Jyoti Sinning Mills Limited": "Manufacturing And Processing",
    "Kalika Microcredit Development Bank Ltd.": "Microfinance",
    "Kalika power Company Ltd": "Hydro Power",
    "Kamana Sewa Bikas Bank Limited": "Development Banks",
    "Kankai Bikas Bank Ltd.": "Development Banks",
    "Karnali Development Bank Limited": "Development Banks",
    "Khanikhola Hydropower Co. Ltd.": "Hydro Power",
    "Kisan Lagubitta Bittiya Sanstha Limited": "Microfinance",
    "Kumari Bank Limited": "Commercial Banks",
    "Kumari Equity Fund": "Mutual Fund",
    "Lalitpur Finance Ltd.": "Finance",
    "Laxmi Bank Limited": "Commercial Banks",
    "Laxmi Equity Fund": "Mutual Fund",
    "Laxmi Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Laxmi Unnati Kosh": "Mutual Fund",
    "Liberty Energy Company Limited": "Hydro Power",
    "Life Insurance Co. Nepal": "Life Insurance",
    "Lumbini Bikas Bank Ltd.": "Development Banks",
    "Lumbini General Insurance Co. Ltd.": "Non Life Insurance",
    "Machhapuchhre Bank Limited": "Commercial Banks",
    "Mahalaxmi Bikas Bank Ltd.": "Development Banks",
    "Mahila Lagubitta Bittiya Sanstha Limited": "Microfinance",
    "Mahila Sahayatra Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Mahuli Samudayik Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Manjushree Finance Ltd.": "Finance",
    "Mega Bank Nepal Ltd.": "Commercial Banks",
    "Mero Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Mirmire Microfinance Development Bank Ltd.": "Microfinance",
    "Miteri Development Bank Limited": "Development Banks",
    "Mithila LaghuBitta Bittiya Sanstha Limited": "Microfinance",
    "Mountain Energy Nepal Limited": "Hydro Power",
    "Mountain Hydro Nepal Limited": "Hydro Power",
    "Muktinath Bikas Bank Ltd.": "Development Banks",
    "Multipurpose Finance Company Limited": "Finance",
    "NABIL BALANCED FUND-2": "Mutual Fund",
    "Nabil Bank Limited": "Commercial Banks",
    "Nabil Equity Fund": "Mutual Fund",
    "Nadep Laghubittiya bittya Sanstha Ltd.": "Microfinance",
    "Narayani Development Bank Limited": "Development Banks",
    "National Hydro Power Company Limited": "Hydro Power",
    "National Life Insurance Co. Ltd.": "Life Insurance",
    "National Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Neco Insurance Co. Ltd.": "Non Life Insurance",
    "Nepal Agro Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Nepal Bangladesh Bank Limited": "Commercial Banks",
    "Nepal Bank Limited": "Commercial Banks",
    "Nepal Bitumin And Barrel Udhyog Limited": "Manufacturing And Processing",
    "Nepal Credit And Commercial Bank Limited": "Commercial Banks",
    "Nepal Doorsanchar Comapany Limited": "Others",
    "Nepal Film Development Company Limited": "Others",
    "Nepal Finance Ltd.": "Finance",
    "Nepal Hydro Developers Ltd.": "Hydro Power",
    "Nepal Infrastructure Bank Limited": "Others",
    "Nepal Insurance Co. Ltd.": "Non Life Insurance",
    "Nepal Investment Bank Limited": "Commercial Banks",
    "Nepal Khadya Udhyog Limited": "Manufacturing And Processing",
    "Nepal Life Insurance Co. Ltd.": "Life Insurance",
    "Nepal Lube Oil Limited": "Manufacturing And Processing",
    "Nepal Reinsurance Company Limited": "Others",
    "Nepal SBI Bank Limited": "Commercial Banks",
    "Nepal Seva Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Nepal Share Markets Ltd.": "Finance",
    "Nepal Tading Limited": "Tradings",
    "Nepal Vanaspati Ghee Udhyog Limited": "Manufacturing And Processing",
    "Nepal Welfare Company Limited": "Tradings",
    "Nerude Laghubita Bikas Bank Limited": "	Microfinance",
    "Ngadi Group Power Ltd.": "Hydro Power",
    "NIBL Pragati Fund": "Mutual Fund",
    "NIBL Samriddhi Fund 1": "Mutual Fund",
    "NIC Asia Balanced Fund": "Mutual Fund",
    "NIC Asia Bank Ltd.": "Commercial Banks",
    "NIC Asia Growth Fund": "Mutual Fund",
    "NIC ASIA Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "NIDC Development Bank Ltd.": "Development Banks",
    "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "NLG Insurance Company Ltd.": "Non Life Insurance",
    "NMB Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "NMB 50": "Mutual Fund",
    "NMB Bank Limited": "Commercial Banks",
    "NMB Hybrid Fund L-1": "Mutual Fund",
    "NRN Infrastructure and Development Limited": "Investment",
    "Om Development Bank Ltd.": "Development Banks",
    "Panchakanya Mai Hydropower Ltd": "Hydro Power",
    "Panchthar Power Compant Limited": "Hydro Power",
    "Pokhara Finance Ltd.": "Finance",
    "Prabhu Bank Limited": "Commercial Banks",
    "Prabhu Insurance Ltd.": "Non Life Insurance",
    "Prabhu Life Insurance Limited": "Life Insurance",
    "Premier Insurance Co. Ltd.": "Non Life Insurance",
    "Prime Commercial Bank Ltd.": "Commercial Banks",
    "Prime Life Insurance Company Limited": "Life Insurance",
    "ProgressiveFinance Limited": "Finance",
    "Prudential Insurance Co. Ltd.": "Non Life Insurance",
    "Radhi Bidyut Company Ltd": "Hydro Power",
    "Raghupati Jute Mills Limited": "Manufacturing And Processing",
    "Rairang Hydropower Development Company Ltd.": "Hydro Power",
    "Rastriya Beema Company Limited": "Non Life Insurance",
    "RASUWAGADHI HYDROPOWER COMPANY LIMITED": "Hydro Power",
    "Reliance Finance Ltd.": "Finance",
    "Reliance Life Insurance Limited": "Life Insurance",
    "Ridi Hydropower Development Company Ltd.": "Hydro Power",
    "RMDC Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "RSDC Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Ru Ru Jalbidhyut Pariyojana Limited": "Hydro Power",
    "SABAIKO LAGHUBITTA BITTIYA SANSTHA LIMITED": "Microfinance",
    "Sadhana Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Sagarmatha Insurance Co. Ltd.": "Non Life Insurance",
    "Sahara Bikas Bank Ltd.": "Development Banks",
    "Sahayogi Bikas Bank Limited": "Development Banks",
    "Salt Trading Corporation": "Tradings",
    "Samata Gharelu Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Samjhana Finance Co. Ltd.": "Finance",
    "Samriddhi Finance Company Limited": "Finance",
    "Samudayik Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Sana Kisan Bikas Bank Ltd": "Microfinance",
    "Sanima Bank Limited": "Commercial Banks",
    "Sanima Equity Fund": "Mutual Fund",
    "Sanima General Insurance Limited": "Non Life Insurance",
    "Sanima Large Cap Fund": "Mutual Fund",
    "Sanima Mai Hydropower Ltd.": "Hydro Power",
    "SANJEN JALAVIDHYUT COMPANY LIMITED": "Hydro Power",
    "Saptakoshi Development Bank Ltd": "Development Banks",
    "Sarathi Nepal Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Shangrila Development Bank Ltd.": "Development Banks",
    "Shikhar Insurance Co. Ltd.": "Non Life Insurance",
    "Shine Resunga Development Bank Ltd.": "Development Banks",
    "Shiva Shree Hydropower Ltd": "Hydro Power",
    "SHIVAM CEMENTS LTD": "Manufacturing And Processing",
    "Shree Bhrikuti Pulp And Paper Limited": "Manufacturing And Processing",
    "Shree Investment Finance Co. Ltd.": "Finance",
    "Shree Ram Sugar Mills Limited": "Manufacturing And Processing",
    "Shrijana Finance (Bittaya Sanstha)": "Finance",
    "Siddhartha Bank Limited": "Commercial Banks",
    "Siddhartha Equity Fund": "Mutual Fund",
    "Siddhartha Equity Orineted Scheme": "Mutual Fund",
    "Siddhartha Insurance Ltd.": "Non Life Insurance",
    "Siddhartha Investment Growth Scheme - 2": "Mutual Fund",
    "Sindhu Bikash Bank Ltd": "Development Banks",
    "Singati Hydro Energy Limited": "Hydro Power",
    "Sparsha Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Standard Chartered Bank Limited": "Commercial Banks",
    "Summit Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Sunrise Bank Limited": "Commercial Banks",
    "Sunrise Bluechip Fund": "Mutual Fund",
    "Sunrise First Mutual Fund": "Mutual Fund",
    "Support Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Surya Life Insurance Company Limited": "Life Insurance",
    "Suryodaya Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Swabalamban Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Swabhimaan Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Swadeshi Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Swarojgar Laghu Bitta Bikas Bank Ltd.": "Microfinance",
    "Synergy Finance Ltd.": "Finance",
    "Synergy Power Development Ltd.": "Hydro Power",
    "Taragaon Regency Hotel Limited": "Hotels",
    "Taragaon Regency Hotels Ltd. Preference Share": "Preferred Stock",
    "Tinau Mission Development Bank Limited": "Development Banks",
    "Unilever Nepal Limited": "Manufacturing And Processing",
    "Union Hydropower Limited": "Hydro Power",
    "United Finance Ltd.": "Finance",
    "United IDI Mardi RB Hydropower Limited.": "Hydro Power",
    "United Insurance Co. (Nepal) Ltd.": "Non Life Insurance",
    "United Modi Hydropower Ltd.": "Hydro Power",
    "UNIVERSAL POWER COMPANY LTD": "Hydro Power",
    "Unnati Sahakarya Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Upper Tamakoshi Hydropower Ltd": "Hydro Power",
    "Vijaya laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Womi Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Yak And Yeti Hotel Limited": "Hotels",
  };
}
