class ListDataModel {
  static Map<String, String> scripCompanyNameData = {
    "ACLBSL": "Aarambha Chautari Laghubitta Bittiya Sanstha Limited",
    "ADBL": "Agriculture Development Bank Limited",
    "AHL": "Asian Hydropower Limited",
    "AHPC": "Arun Valley Hydropower Development Co. Ltd.",
    "AKJCL": "Ankhu Khola Jalvidhyut Company Ltd",
    "AKPL": "Arun Kabeli Power Ltd.",
    "ALBSL": "Asha Laghubitta Bittiya Sanstha Limited",
    "ALICL": "Asian Life Insurance Co. Limited",
    "ANLB": "Aatmanirbhar Laghubitta Bittiya Sanstha Limited",
    "API": "Api Power Company Ltd.",
    "AVYAN": "Aviyan Laghubitta Bittiya Sanstha Limited",
    "BARUN": "Barun Hydropower Co. Ltd.",
    "BBC": "Bishal Bazar Company Limited",
    "BEDC": " Bhugol Energy Development Company Limited ",
    "BFC": "Best Finance Company Ltd.",
    "BGWT": "Bhagawati Hydropower Development Company Ltd.",
    "BHDC": "Bindyabasini Hydropower Development Company Limited",
    "BHL": "Balephi Hydropower Limited",
    "BHPL": "Barahi Hydropower Public Limited",
    "BNHC": "Buddhabhumi Nepal Hydropower Company Limited",
    "BNT": "Bottlers Nepal ",
    "BPCL": "Butwal Power Company Limited",
    "C30MF": "Citizens Super 30 Mutual Fund",
    "CBBL": "Chhimek Laghubitta Bittiya Sanstha Limited",
    "CBLD88": "Civil Bank Debenture 2088",
    "CCBD88": "Century Debenture 2088",
    "CFCL": "Central Finance Co. Ltd.",
    "CGH": "Chandragiri Hills Limited",
    "CHCL": "Chilime Hydropower Company Limited",
    "CHDC": "CEDB Hydropower Development Company Limited",
    "CHL": "Chhyangdi Hydropower Ltd.",
    "CIT": "Citizen Investment Trust",
    "CITY": "City Hotel Limited",
    "CKHL": "Chirkhwa Hydropower Limited",
    "CLI": "Citizen Life Insurance Company Limited",
    "CMF1": "Citizens Mutual Fund -1",
    "CMF2": "CITIZENS MUTUAL FUND 2",
    "CORBL": "Corporate Development Bank Limited",
    "CYCL": "CYC Nepal Laghubitta Bittiya Sanstha Limited",
    "CZBIL": "Citizen Bank International Limited",
    "DDBL": "Deprosc Laghubitta Bittiya Sanstha Limited",
    "DHPL": "Dibyashwori Hydropower Ltd.",
    "DLBS": "Dhaulagiri Laghubitta Bittiya Sanstha Limited",
    "DOLTI": "Dolti Power Company Limited",
    "DORDI": "Dordi Khola Jal Bidyut Company Limited",
    "EBL": "Everest Bank Limited",
    "EDBL": "Excel Development Bank Ltd.",
    "EHPL": "Eastern Hydropower Limited",
    "ENL": "Emerging Nepal Limited",
    "FMDBL": "First Micro Finance Laghubitta Bittiya Sanstha Limited",
    "FOWAD": "Forward Microfinance Laghubitta Bittiya Sanstha Ltd.",
    "GBBD85": "Garima Debenture, 2085",
    "GBBL": "Garima Bikas Bank Limited",
    "GBIME": "Global IME Bank Limited",
    "GBLBS": "Grameen Bikas Laghubitta Bittiya Sanstha Ltd.",
    "GCIL": "Ghorahi Cement Industry Limited",
    "GFCL": "Goodwill Finance Co. Ltd.",
    "GHL": "Ghalemdi Hydro Limited",
    "GIBF1": "Global IME Balanced Fund-1",
    "GILB": "Global IME Laghubitta Bittiya Sanstha Ltd.",
    "GLBSL": "Gurans Laghubitta Bittiya Sanstha Limited",
    "GLH": "Greenlife Hydropower Limited",
    "GMFBS": "Ganapati Microfinance Bittiya Sanstha Ltd",
    "GMFIL": "Guheshowori Merchant Bank & Finance Co. Ltd.",
    "GRDBL": "Green Development Bank Ltd.",
    "GUFL": "Gurkhas Finance Ltd.",
    "GVL": "Green Ventures Limited",
    "GWFD83": "12% Goodwill finance Debenture 2083",
    "H8020": "Himalayan 80-20",
    "HATHY": "Hathway Investment Nepal Limited",
    "HBL": "Himalayan Bank Limited",
    "HDHPC": "Himal Dolakha Hydropower Company Limited",
    "HDL": "Himalayan Distillery Limited",
    "HEI": "Himalayan Everest Insurance Limited",
    "HEIP": "Himalayan Everest Insurance Limited Promoter",
    "HHL": "Himalayan Hydropower Limited",
    "HIDCL": "Hydorelectricity Investment and Development Company Ltd",
    "HIDCLP":
        "Hydroelectricity Investment and Development Company Limited Promoter Share",
    "HLBSL": "Himalayan Laghubitta Bittiya Sanstha Limited",
    "HLI": "Himalayan Life Insurance Limited",
    "HPPL": "Himalayan Power Partner Ltd.",
    "HRL": "Himalayan Reinsurance Limited",
    "HURJA": "Himalaya Urja Bikas Company Limited",
    "ICFC": "ICFC Finance Limited",
    "IGI": "IGI Prudential Insurance Company Limited",
    "IHL": "Ingwa Hydropower Limited",
    "ILBS": "Infinity Laghubitta Bittiya Sanstha Limited",
    "ILI": "IME Life Insurance Company Limited",
    "JALPA": "Jalpa Samudayik Laghubitta Bittiya Sanstha Limited",
    "JBBL": "Jyoti Bikas Bank Limited",
    "JBLB": "Jeevan Bikas Laghubitta Bittiya Sanstha Limited",
    "JFL": "Janaki Finance Ltd.",
    "JOSHI": "Joshi Hydropower Development Company Ltd",
    "JSLBB": "Janautthan Samudayic Laghubitta Bittiya Sanstha Limited",
    "KBL": "Kumari Bank Limited",
    "KBLD86": "10.25% Kumari Bank Debenture 2086",
    "KBSH": "Kutheli Bukhari Small Hydropower Limited",
    "KDBY": "Kumari Dhanabriddhi Yojana",
    "KDL": "Kalinchowk Darshan Limited",
    "KEF": "Kumari Equity Fund",
    "KKHC": "Khanikhola Hydropower Co. Ltd.",
    "KLBSL": "Kisan Lagubitta Bittiya Sanstha Limited",
    "KMCDB": "Kalika Laghubitta Bittiya Sanstha Limited",
    "KPCL": "Kalika power Company Ltd",
    "KRBL": "Karnali Development Bank Limited",
    "KSBBL": "Kamana Sewa Bikas Bank Limited",
    "KSBBLD87": "9% Kamana Sewa Bikas Bank Limited Debenture 2087",
    "LBBL": "Lumbini Bikas Bank Ltd.",
    "LBBLD89": "11% L.B.B.L. Debenture 2089",
    "LEC": "Liberty Energy Company Limited",
    "LEMF": "Laxmi Equity Fund",
    "LICN": "Life Insurance Co. Nepal",
    "LLBS": "Laxmi Laghubitta Bittiya Sanstha Ltd.",
    "LSL": "Laxmi Sunrise Bank Limited",
    "LUK": "Laxmi unnati Kosh",
    "MAKAR": "Makar Jitumaya Suri Hydropower Limited",
    "MANDU": "Mandu Hydropower Ltd.",
    "MBJC": "Madhya Bhotekoshi Jalavidyut Company Limited",
    "MBL": "Machhapuchchhre Bank Limited",
    "MCHL": "Menchhiyam Hydropower Limited",
    "MDB": "Miteri Development Bank Limited",
    "MEHL": "Manakamana Engineering Hydropower Limited",
    "MEL": "Modi Energy Limited",
    "MEN": "Mountain Energy Nepal Limited",
    "MERO": "Meromicrofinance Laghubitta Bittiya Sanstha Ltd.",
    "MFIL": "Manjushree Finance Ltd.",
    "MFLD85": "9.5% Manjushree Finance Limited Debenture 2085",
    "MHCL": "Molung Hydropower Company Limited",
    "MHL": "Mandakini Hydropower Limited",
    "MHNL": "Mountain Hydro Nepal Limited",
    "MKCL": "Muktinath Krishi Company Limited",
    "MKHC": "Maya Khola Hydropower Company Limited",
    "MKHL": "Mai Khola Hydropower Limited",
    "MKJC": "Mailung Khola Jal Vidhyut Company  Limited",
    "MKLB": "Manakamana Smart Laghubitta Bittiya Sanstha Limited",
    "MLBBL": "Mithila Laghubitta Bittiya Sanstha Ltd.",
    "MLBL": "Mahalaxmi Bikas Bank Ltd.",
    "MLBS": "Manushi Laghubitta Bittiya Sanstha Limited",
    "MLBSL": "Mahila Laghubitta Bittiya Sanstha Limited",
    "MMF1": "Mega Mutual Fund-1",
    "MMKJL": "Mathillo Mailun Khola Jalvidhyut Limited",
    "MNBBL": "Muktinath Bikas Bank Ltd.",
    "MPFL": "Multipurpose Finance Company Limited",
    "MSHL": "Mid-Solu Hydropower Limited",
    "MSLB": "Mahuli Laghubitta Bittiya Sanstha Ltd.",
    "NABBC": "Narayani Development Bank Limited",
    "NABIL": "Nabil Bank Limited",
    "NADEP": "Nadep Laghubitta Bittiya Sanstha Ltd.",
    "NBF2": "NABIL BALANCED FUND-2",
    "NBF3": "nabil Balanced Fund-3",
    "NBL": "Nepal Bank Limited",
    "NBLD85": "8% Nabil Debenture 2085",
    "NBLD87": "8.5% Nepal Bank Debenture 2087",
    "NCCD86": "9.5% NCC Debenture 2086",
    "NESDO": "NESDO Sambridha Laghubitta Bittiye Sanstha Limited",
    "NFS": "Nepal Finance Ltd.",
    "NGPL": "Ngadi Group Power Ltd.",
    "NHDL": "Nepal Hydro Developers Ltd.",
    "NHPC": "National Hydro Power Company Limited",
    "NIBD2082": "10.5% Nepal Investment Debenture 2082",
    "NIBLGF": "NIBL Growth Fund",
    "NIBSF2": "NIBL Samriddhi Fund 2",
    "NICA": "NIC Asia Bank Ltd.",
    "NICAD8283": "11% NIC Asia Debenture 082/83",
    "NICBF": "NIC Asia Balanced Fund",
    "NICFC": "NIC ASIA Flexi CAP Fund",
    "NICGF": "NIC Asia Growth Fund",
    "NICGF2": "NIC Asia Growth Fund-2",
    "NICL": "Nepal Insurance Co. Ltd.",
    "NICLBSL": "NIC Asia Laghubitta Biitiya Sanstha Limited",
    "NICSF": "NIC Asia Select - 30 ",
    "NIFRA": "Nepal Infrastructure Bank Limited",
    "NIFRAUR85/86": "Nifra Urja 7% -2085/86",
    "NIL": "Neco Insurance Co. Ltd.",
    "NIMB": "Nepal Investment Mega Bank Limited ",
    "NIMBD90": "10% NIMB Debenture 2090",
    "NIMBPO": "Nepal Investment Mega Bank Ltd. Promoter Share ",
    "NLG": "NLG Insurance Company Ltd.",
    "NLIC": "Nepal Life Insurance Co. Ltd.",
    "NLICL": "National Life Insurance Co. Ltd.",
    "NMB": "NMB Bank Limited",
    "NMB50": "NMB 50",
    "NMBD87/88": "8.50% NMB Rinpatra 2087/88",
    "NMBMF": "NMB Laghubitta Bittiya Sanstha Ltd.",
    "NMFBS": "National Laghubitta Bittiya Sanstha Limited",
    "NRIC": "Nepal Re-Insurance Company Limited",
    "NRM": "Nepal Republic Media Limited",
    "NRN": "NRN Infrastructure and Development Limited",
    "NSIF2": "NMB Sulav Investment Fund - 2",
    "NTC": "Nepal Doorsanchar Comapany Limited",
    "NUBL": "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited",
    "NWCL": "Nepal Warehousing Company Limited",
    "NYADI": "Nyadi Hydropower Limited",
    "OHL": "Oriental Hotels Limited",
    "PBD88": "10% Prime Debenture 2088",
    "PBLD84": "10% Prabhu Bank Debenture 2084 ",
    "PBLD87": "8.5% Prabhu Bank Debenture 2087",
    "PCBL": "Prime Commercial Bank Ltd.",
    "PFL": "Pokhara Finance Ltd.",
    "PHCL": "Peoples Hydropower Company Limited",
    "PMHPL": "Panchakanya Mai Hydropower Ltd",
    "PMLI": "Prabhu Mahalaxmi Life Insurance Limited",
    "PPCL": "Panchthar Power Company Limited",
    "PPL": "People",
    "PRIN": "Prabhu Insurance Ltd.",
    "PROFL": "Progressive Finance Limited",
    "PRSF": "Prabhu Smart Fund",
    "PRVU": "Prabhu Bank Limited",
    "PRVUPO": "Prabhu Bank Limited Promoter Share",
    "PSF": "Prabhu Select Fund",
    "RADHI": "Radhi Bidyut Company Ltd",
    "RAWA": "Rawa Energy Development Limited",
    "RBBD83": "8.5% RBBL Debenture 2083",
    "RBCL": "Rastriya Beema Company Limited",
    "RBCLPO": "Rastriya Beema Company Limited Promoter Share",
    "RFPL": "River Falls Power Limited",
    "RHGCL": "Rapti Hydro and General Construction Limited",
    "RHPL": "RASUWAGADHI HYDROPOWER COMPANY LIMITED",
    "RIDI": "Ridi Power Company Limited",
    "RLFL": "Reliance Finance Ltd.",
    "RMF1": "RBB Mutual Fund 1",
    "RMF2": "RBB Mutual Fund 2",
    "RNLI": "Reliable Nepal Life Insurance Limited",
    "RSDC": "RSDC Laghubitta Bittiya Sanstha Ltd.",
    "RURU": "Ru Ru Jalbidhyut Pariyojana Limited",
    "SABSL": "SABAIKO LAGHUBITTA BITTIYA SANSTHA LIMITED",
    "SADBL": "Shangrila Development Bank Ltd.",
    "SAEF": "Sanima Equity Fund",
    "SAGF": "Sanima Growth Fund",
    "SAHAS": "Sahas Urja Limited",
    "SALICO": "Sagarmatha Lumbini Insurance Co. Limited",
    "SAMAJ": "Samaj Laghubittya Bittiya Sanstha Limited",
    "SANIMA": "Sanima Bank Limited",
    "SAPDBL": "Saptakoshi Development Bank Ltd",
    "SARBTM": "Sarbottam Cement Limited",
    "SBCF": "Sunrise Bluechip Fund",
    "SBI": "Nepal SBI Bank Limited",
    "SBL": "Siddhartha Bank Limited",
    "SCB": "Standard Chartered Bank Limited",
    "SDBD87": "9% Shangri-la Development Bank Debenture 2087",
    "SDLBSL": "Sadhana Laghubitta Bittiya Sanstha Limited",
    "SFCL": "Samriddhi Finance Company Limited",
    "SFEF": "Sunrise Focused Equity Fund",
    "SFMF": "Sunrise First Mutual Fund",
    "SGHC": "Swet-Ganga Hydropower & Construction Limited ",
    "SGIC": "Sanima GIC Insurance Limited",
    "SHEL": "Singati Hydro Energy Limited",
    "SHINE": "Shine Resunga Development Bank Ltd.",
    "SHIVM": "SHIVAM CEMENTS LTD",
    "SHL": "Soaltee Hotel Limited",
    "SHLB": "Shrijanshil Laghubitta Bittiya Sanstha Limited",
    "SHPC": "Sanima Mai Hydropower Ltd.",
    "SICL": "Shikhar Insurance Co. Ltd.",
    "SIFC": "Shree Investment Finance Co. Ltd.",
    "SIGS2": "Siddhartha Investment Growth Scheme - 2",
    "SIGS3": "Siddhartha Investment Growth Scheme 3	",
    "SIKLES": "Sikles Hydropower Limited",
    "SINDU": "Sindhu Bikash Bank Ltd",
    "SJCL": "SANJEN JALAVIDHYUT COMPANY LIMITED",
    "SJLIC": "SuryaJyoti Life Insurance Company Limited",
    "SKBBL": "Sana Kisan Bikas Laghubitta Bittiya sanstha Limited.",
    "SLBBL": "Swarojgar Laghubitta Bittiya Sanstha Ltd.",
    "SLCF": "Sanima Large Cap Fund",
    "SMATA": "Samata Gharelu Laghubitta Bittiya Sanstha Limited",
    "SMB": "Support Microfinance Bittiya Sanstha Ltd.",
    "SMFBS": "Swabhimaan Laghubitta Bittiya Sanstha Ltd",
    "SMH": "Super Mai Hydropower Limited",
    "SMHL": "Super Madi Hydropower Limited",
    "SMJC": "Sagarmatha Jalabidhyut Company Limited",
    "SNLI": "Sun Nepal Life Insurance Company Limited",
    "SONA": "Sonapur Minerals and Oil Limited",
    "SPC": "Samling Power Company Limited",
    "SPDL": "Synergy Power Development Ltd.",
    "SPHL": "Sayapatri Hydropower Limited",
    "SPIL": "Siddhartha Premier Insurance Limited",
    "SPL": "Shuvam Power Company Limited",
    "SRLI": "Sanima Reliance Life Insurance Limited",
    "SSHL": "Shiva Shree Hydropower Limited",
    "STC": "Salt Trading Corporation",
    "SWBBL": "Swabalamban Laghubitta Bittiya Sanstha Limited",
    "SWMF": "Suryodaya Womi Laghubitta Bittiya Sanstha Limited ",
    "TAMOR": "Sanima Middle Tamor Hydropower Limited",
    "TPC": "Terhathum Power Company Limited",
    "TRH": "Taragaon Regency Hotel Limited",
    "TSHL": "Three Star Hydropower Limited",
    "TVCL": "Trishuli Jal Vidhyut Company Limited",
    "UAIL": "United Ajod Insurance Limited ",
    "UHEWA": "Upper Hewakhola Hydropower Company Limited",
    "ULBSL": "Upakar Laghubitta Bittiya Sanstha Limited",
    "ULHC": "Upper Lohore Khola Hydropower Company Limited",
    "UMHL": "United Modi Hydropower Ltd.",
    "UMRH": "United IDI Mardi RB Hydropower Limited.",
    "UNHPL": "Union Hydropower Limited",
    "UNL": "Unilever Nepal Limited",
    "UNLB": "Unique Nepal Laghubitta Bittiya Sanstha Limited",
    "UPCL": "UNIVERSAL POWER COMPANY LTD",
    "UPPER": "Upper Tamakoshi Hydropower Ltd",
    "USHEC": "Upper Solu Hydro Electric Company Limited ",
    "USHL": "Upper Syange  Hydropower Limited",
    "USLB": "Unnati Sahakarya Laghubitta Bittiya Sanstha Limited",
    "VLBS": "Vijaya laghubitta Bittiya Sanstha Ltd.",
    "VLUCL": "Vision Lumbini Urja Company Limited",
    "WNLB": "WEAN Nepal Laghubitta Bittiya Sanstha Limited",
  };

  static Map<String, String> companySectorData = {
    "10 % NMB DEBENTURE 2085": "Corporate Debenture",
    "10% Himalayan Bank Debenture 2083": "Corporate Debenture",
    "10% Laxmi Bank Debenture 2086": "Corporate Debenture",
    "10% Nabil Debenture 2082": "Corporate Debenture",
    "10% Nepal SBI Bank Debenture 2086": "Corporate Debenture",
    "10% NIC Asia Debenture 2085/86": "Corporate Debenture",
    "10% Prabhu Bank Debenture 2084": "Corporate Debenture",
    "10% Sanima Bank Limited Debenture": "Corporate Debenture",
    "10% Sunrise Debenture 2080": "Corporate Debenture",
    "10.25% Citizens Bank Debenture 2086": "Corporate Debenture",
    "10.25% GLOBAL IME BANK LTD. DEBENTURE 2080/81": "Corporate Debenture",
    "10.25% KBL Debenture 2086": "Corporate Debenture",
    "10.25% Machhapuchhre Bank Debenture 2085": "Corporate Debenture",
    "10.25% NBBL Debenture 2085": "Corporate Debenture",
    "10.25% NIC Asia Debenture 2083/84": "Corporate Debenture",
    "10.25% Prabhu Bank Debenture 2086": "Corporate Debenture",
    "10.25% SBL Debenture 2083": "Corporate Debenture",
    "10.25% Sunrise Bank Debenture 2083": "Corporate Debenture",
    "10.35% Agricultural Bank Debenture 2083": "Corporate Debenture",
    "10.5 % NEPAL INVESTMENT DEBENTURE 2082": "Corporate Debenture",
    "10.50% SBL Debenture 2082": "Corporate Debenture",
    "11% NIC Asia Debenture 082/83": "Corporate Debenture",
    "12 % Goodwill Finance Limited Debenture 2083": "Corporate Debenture",
    "12% ICFC Finance Limited Debenture 2083": "Corporate Debenture",
    "8% BOK Debenture 2079": "Corporate Debenture",
    "8% EBL Debenture 2078": "Corporate Debenture",
    "8.5% Nepal Investment Bank Debenture 2084": "Corporate Debenture",
    "8.5% Sanima Debenture 2087": "Corporate Debenture",
    "8.5% SBL Debenture 2084": "Corporate Debenture",
    "9% NIC Asia Debenture 2081/82": "Corporate Debenture",
    "9.5% Manjushree Finance Limited Debenture 2085": "Corporate Debenture",
    "9.5% NCC Debenture 2086": "Corporate Debenture",
    "Aarambha Chautari Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "ADHIKHOLA LAGHUBITTA BITTIYA SANSTHA LIMITED": "Microfinance",
    "Agriculture Development Bank Limited": "Commercial Banks",
    "Asian Hydropower Limited": "Hydro Power",
    "Ajod Insurance Limited": "Non Life Insurance",
    "Ankhu Khola Jalvidhyut Company Ltd": "Hydro Power",
    "Api Power Company Ltd.": "Hydro Power",
    "Arambha Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Arun Kabeli Power Ltd.": "Hydro Power",
    "Arun Valley Hydropower Development Co. Ltd.": "Hydro Power",
    "Arun Vanaspati Udhyog Limited": "Manufacturing And Processing",
    "Asha Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Asian Life Insurance Co. Limited": "	Life Insurance",
    "Bank of Kathmandu Ltd.": "Commercial Banks",
    "Barun Hydropower Co. Ltd.": "Hydro Power",
    "Best Finance Company Ltd.": "Finance",
    "Bhargav Bikash Bank Ltd.": "Development Banks",
    "Birat Shoe Limited": "Manufacturing And Processing",
    "Bishal Bazar Company Limited": "Tradings",
    "Bottlers Nepal (Balaju) Limited": "Manufacturing And Processing",
    "Bottlers Nepal (Terai) Limited": "Manufacturing And Processing",
    "Butwal Power Company Limited": "Hydro Power",
    "Butwal Spinning Mills Limited": "Manufacturing And Processing",
    "Capital Merchant Bank & Finance Co. Ltd.": "Finance",
    "CEDB Hydropower Development Company Limited": "Investment",
    "Central Finance Co. Ltd.": "Finance",
    "Century Commercial Bank Ltd.": "Commercial Banks",
    "Chhimek Laghubitta Bikas Bank Limited": "Microfinance",
    "Chhyangdi Hydropower Ltd.": "Hydro Power",
    "Chilime Hydropower Company Limited": "Hydro Power",
    "Citizen Bank International Limited": "Commercial Banks",
    "Citizen Investment Trust": "Investment",
    "Citizens Mutual Fund -1": "Mutual Fund",
    "CITIZENS MUTUAL FUND 2": "Mutual Fund",
    "City Express Finance Co. Limited": "Finance",
    "Civil Bank Ltd": "Commercial Banks",
    "Civil Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Corporate Development Bank Limited": "Development Banks",
    "Crystal Finance Ltd.": "Finance",
    "Deprosc Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Dibyashwori Hydropower Ltd.": "Hydro Power",
    "Everest Bank Limited": "Commercial Banks",
    "Everest Bank Limited Con. Pref.": "Preferred Stock",
    "Everest Insurance Co. Ltd.": "Non Life Insurance",
    "Excel Development Bank Ltd.": "Development Banks",
    "First Micro Finance Development Bank Ltd.": "Microfinance",
    "Fleur Himalayan Limited": "Manufacturing And Processing",
    "Forward Community Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Ganapati Microfinance Bittiya Sanstha Limited": "Microfinance",
    "Gandaki Bikas Bank Limited": "Development Banks",
    "Garima Bikas Bank Limited": "Development Banks",
    "General Insurance Company Nepal Ltd": "Non Life Insurance",
    "Ghalemdi Hydro Limited": "Hydro Power",
    "Ghodighoda Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Global IME Bank Limited": "Commercial Banks",
    "Global IME Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Global IME Samunnat Scheme-1": "Mutual Fund",
    "Goodwill Finance Co. Ltd.": "Finance",
    "Gorakhkali Rubber Udhyog Limited": "Manufacturing And Processing",
    "Grameen Bikas Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Green Development Bank Ltd.": "Development Banks",
    "GreenLife Hydropower Limited": "Finance",
    "Guheshowori Merchant Bank & Finance Co. Ltd.": "Finance",
    "Gurans Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Gurans Life Insurance Company Ltd.": "Life Insurance",
    "Gurkhas Finance Ltd.": "Finance",
    "Hamro Bikas Bank Ltd.": "Development Banks",
    "Harisiddhi Brick And Tiles Limited": "Manufacturing And Processing",
    "Hathway Finance Company Limited": "Finance",
    "Himal Dolakha Hydropower Company Limited": "Hydro Power",
    "Himalaya Urja Bikas Company Limited": "Hydro Power",
    "Himalayan Bank Limited": "Commercial Banks",
    "Himalayan Distillery Limited": "Manufacturing And Processing",
    "Himalayan Finance Limited (Bittiya Sanstha)": "Finance",
    "Himalayan General Insurance Co. Ltd": "Non Life Insurance",
    "Himalayan Power Partner Ltd.": "Hydro Power",
    "Hydorelectricity Investment and Development Company Ltd": "Investment",
    "ICFC Finance Limited": "Finance",
    "IME General Insurance Ltd.": "Non Life Insurance",
    "Infinity Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Janaki Finance Ltd.": "Finance",
    "Janata Bank Nepal Ltd.": "Commercial Banks",
    "Janautthan Samudayic Laghubitta Bikas Bank Ltd.": "Microfinance",
    "Joshi Hydropower Development Company Ltd": "Hydro Power",
    "Jyoti Bikas Bank Limited": "Development Banks",
    "Jyoti Life Insurance Ltd": "Life Insurance",
    "Jyoti Sinning Mills Limited": "Manufacturing And Processing",
    "Kalika Microcredit Development Bank Ltd.": "Microfinance",
    "Kalika power Company Ltd": "Hydro Power",
    "Kamana Sewa Bikas Bank Limited": "Development Banks",
    "Kankai Bikas Bank Ltd.": "Development Banks",
    "Karnali Development Bank Limited": "Development Banks",
    "Khanikhola Hydropower Co. Ltd.": "Hydro Power",
    "Kisan Lagubitta Bittiya Sanstha Limited": "Microfinance",
    "Kumari Bank Limited": "Commercial Banks",
    "Kumari Equity Fund": "Mutual Fund",
    "Lalitpur Finance Ltd.": "Finance",
    "Laxmi Bank Limited": "Commercial Banks",
    "Laxmi Equity Fund": "Mutual Fund",
    "Laxmi Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Laxmi Unnati Kosh": "Mutual Fund",
    "Liberty Energy Company Limited": "Hydro Power",
    "Life Insurance Co. Nepal": "Life Insurance",
    "Lumbini Bikas Bank Ltd.": "Development Banks",
    "Lumbini General Insurance Co. Ltd.": "Non Life Insurance",
    "Machhapuchhre Bank Limited": "Commercial Banks",
    "Mahalaxmi Bikas Bank Ltd.": "Development Banks",
    "Mahila Lagubitta Bittiya Sanstha Limited": "Microfinance",
    "Mahila Sahayatra Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Mahuli Samudayik Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Manjushree Finance Ltd.": "Finance",
    "Mega Bank Nepal Ltd.": "Commercial Banks",
    "Mero Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Mirmire Microfinance Development Bank Ltd.": "Microfinance",
    "Miteri Development Bank Limited": "Development Banks",
    "Mithila LaghuBitta Bittiya Sanstha Limited": "Microfinance",
    "Mountain Energy Nepal Limited": "Hydro Power",
    "Mountain Hydro Nepal Limited": "Hydro Power",
    "Muktinath Bikas Bank Ltd.": "Development Banks",
    "Multipurpose Finance Company Limited": "Finance",
    "NABIL BALANCED FUND-2": "Mutual Fund",
    "Nabil Bank Limited": "Commercial Banks",
    "Nabil Equity Fund": "Mutual Fund",
    "Nadep Laghubittiya bittya Sanstha Ltd.": "Microfinance",
    "Narayani Development Bank Limited": "Development Banks",
    "National Hydro Power Company Limited": "Hydro Power",
    "National Life Insurance Co. Ltd.": "Life Insurance",
    "National Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Neco Insurance Co. Ltd.": "Non Life Insurance",
    "Nepal Agro Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Nepal Bangladesh Bank Limited": "Commercial Banks",
    "Nepal Bank Limited": "Commercial Banks",
    "Nepal Bitumin And Barrel Udhyog Limited": "Manufacturing And Processing",
    "Nepal Credit And Commercial Bank Limited": "Commercial Banks",
    "Nepal Doorsanchar Comapany Limited": "Others",
    "Nepal Film Development Company Limited": "Others",
    "Nepal Finance Ltd.": "Finance",
    "Nepal Hydro Developers Ltd.": "Hydro Power",
    "Nepal Infrastructure Bank Limited": "Others",
    "Nepal Insurance Co. Ltd.": "Non Life Insurance",
    "Nepal Investment Bank Limited": "Commercial Banks",
    "Nepal Khadya Udhyog Limited": "Manufacturing And Processing",
    "Nepal Life Insurance Co. Ltd.": "Life Insurance",
    "Nepal Lube Oil Limited": "Manufacturing And Processing",
    "Nepal Reinsurance Company Limited": "Others",
    "Nepal SBI Bank Limited": "Commercial Banks",
    "Nepal Seva Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Nepal Share Markets Ltd.": "Finance",
    "Nepal Tading Limited": "Tradings",
    "Nepal Vanaspati Ghee Udhyog Limited": "Manufacturing And Processing",
    "Nepal Welfare Company Limited": "Tradings",
    "Nerude Laghubita Bikas Bank Limited": "	Microfinance",
    "Ngadi Group Power Ltd.": "Hydro Power",
    "NIBL Pragati Fund": "Mutual Fund",
    "NIBL Samriddhi Fund 1": "Mutual Fund",
    "NIC Asia Balanced Fund": "Mutual Fund",
    "NIC Asia Bank Ltd.": "Commercial Banks",
    "NIC Asia Growth Fund": "Mutual Fund",
    "NIC ASIA Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "NIDC Development Bank Ltd.": "Development Banks",
    "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "NLG Insurance Company Ltd.": "Non Life Insurance",
    "NMB Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "NMB 50": "Mutual Fund",
    "NMB Bank Limited": "Commercial Banks",
    "NMB Hybrid Fund L-1": "Mutual Fund",
    "NRN Infrastructure and Development Limited": "Investment",
    "Om Development Bank Ltd.": "Development Banks",
    "Panchakanya Mai Hydropower Ltd": "Hydro Power",
    "Panchthar Power Compant Limited": "Hydro Power",
    "Pokhara Finance Ltd.": "Finance",
    "Prabhu Bank Limited": "Commercial Banks",
    "Prabhu Insurance Ltd.": "Non Life Insurance",
    "Prabhu Life Insurance Limited": "Life Insurance",
    "Premier Insurance Co. Ltd.": "Non Life Insurance",
    "Prime Commercial Bank Ltd.": "Commercial Banks",
    "Prime Life Insurance Company Limited": "Life Insurance",
    "ProgressiveFinance Limited": "Finance",
    "Prudential Insurance Co. Ltd.": "Non Life Insurance",
    "Radhi Bidyut Company Ltd": "Hydro Power",
    "Raghupati Jute Mills Limited": "Manufacturing And Processing",
    "Rairang Hydropower Development Company Ltd.": "Hydro Power",
    "Rastriya Beema Company Limited": "Non Life Insurance",
    "RASUWAGADHI HYDROPOWER COMPANY LIMITED": "Hydro Power",
    "Reliance Finance Ltd.": "Finance",
    "Reliance Life Insurance Limited": "Life Insurance",
    "Ridi Hydropower Development Company Ltd.": "Hydro Power",
    "RMDC Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "RSDC Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Ru Ru Jalbidhyut Pariyojana Limited": "Hydro Power",
    "SABAIKO LAGHUBITTA BITTIYA SANSTHA LIMITED": "Microfinance",
    "Sadhana Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Sagarmatha Insurance Co. Ltd.": "Non Life Insurance",
    "Sahara Bikas Bank Ltd.": "Development Banks",
    "Sahayogi Bikas Bank Limited": "Development Banks",
    "Salt Trading Corporation": "Tradings",
    "Samata Gharelu Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Samjhana Finance Co. Ltd.": "Finance",
    "Samriddhi Finance Company Limited": "Finance",
    "Samudayik Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Sana Kisan Bikas Bank Ltd": "Microfinance",
    "Sanima Bank Limited": "Commercial Banks",
    "Sanima Equity Fund": "Mutual Fund",
    "Sanima General Insurance Limited": "Non Life Insurance",
    "Sanima Large Cap Fund": "Mutual Fund",
    "Sanima Mai Hydropower Ltd.": "Hydro Power",
    "SANJEN JALAVIDHYUT COMPANY LIMITED": "Hydro Power",
    "Saptakoshi Development Bank Ltd": "Development Banks",
    "Sarathi Nepal Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Shangrila Development Bank Ltd.": "Development Banks",
    "Shikhar Insurance Co. Ltd.": "Non Life Insurance",
    "Shine Resunga Development Bank Ltd.": "Development Banks",
    "Shiva Shree Hydropower Ltd": "Hydro Power",
    "SHIVAM CEMENTS LTD": "Manufacturing And Processing",
    "Shree Bhrikuti Pulp And Paper Limited": "Manufacturing And Processing",
    "Shree Investment Finance Co. Ltd.": "Finance",
    "Shree Ram Sugar Mills Limited": "Manufacturing And Processing",
    "Shrijana Finance (Bittaya Sanstha)": "Finance",
    "Siddhartha Bank Limited": "Commercial Banks",
    "Siddhartha Equity Fund": "Mutual Fund",
    "Siddhartha Equity Orineted Scheme": "Mutual Fund",
    "Siddhartha Insurance Ltd.": "Non Life Insurance",
    "Siddhartha Investment Growth Scheme - 2": "Mutual Fund",
    "Sindhu Bikash Bank Ltd": "Development Banks",
    "Singati Hydro Energy Limited": "Hydro Power",
    "Sparsha Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Standard Chartered Bank Limited": "Commercial Banks",
    "Summit Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Sunrise Bank Limited": "Commercial Banks",
    "Sunrise Bluechip Fund": "Mutual Fund",
    "Sunrise First Mutual Fund": "Mutual Fund",
    "Support Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Surya Life Insurance Company Limited": "Life Insurance",
    "Suryodaya Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Swabalamban Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Swabhimaan Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Swadeshi Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Swarojgar Laghu Bitta Bikas Bank Ltd.": "Microfinance",
    "Synergy Finance Ltd.": "Finance",
    "Synergy Power Development Ltd.": "Hydro Power",
    "Taragaon Regency Hotel Limited": "Hotels",
    "Taragaon Regency Hotels Ltd. Preference Share": "Preferred Stock",
    "Tinau Mission Development Bank Limited": "Development Banks",
    "Unilever Nepal Limited": "Manufacturing And Processing",
    "Union Hydropower Limited": "Hydro Power",
    "United Finance Ltd.": "Finance",
    "United IDI Mardi RB Hydropower Limited.": "Hydro Power",
    "United Insurance Co. (Nepal) Ltd.": "Non Life Insurance",
    "United Modi Hydropower Ltd.": "Hydro Power",
    "UNIVERSAL POWER COMPANY LTD": "Hydro Power",
    "Unnati Sahakarya Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Upper Tamakoshi Hydropower Ltd": "Hydro Power",
    "Vijaya laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Womi Microfinance Bittiya Sanstha Ltd.": "Microfinance",
    "Yak And Yeti Hotel Limited": "Hotels",
    "Aatmanirbhar Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Aviyan Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Bhugol Energy Development Company": "Hydro Power",
    "Bhagawati Hydropower Development Company Ltd.": "Hydro Power",
    "Bindyabasini Hydropower Development Company Limited": "Hydro Power",
    "Balephi Hydropower Limited": "Hydro Power",
    "Barahi Hydropower Public Limited": "Hydro Power",
    "Buddhabhumi Nepal Hydropower Company Limited": "Hydro Power",
    " Bhugol Energy Development Company Limited ": "BEDC",
    "Bottlers Nepal ": "BNT",
    "Citizens Super 30 Mutual Fund": "C30MF",
    "Chhimek Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Civil Bank Debenture 2088": "Debenture",
    "Century Debenture 2088": "Debenture",
    "Chandragiri Hills Limited": "Hotels",
    "City Hotel Limited": "Hotels",
    "Chirkhwa Hydropower Limited": "Hydro Power",
    "Citizen Life Insurance Company Limited": "Life Insurance",
    "CYC Nepal Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Dhaulagiri Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Dolti Power Company Limited": "Hydro Power",
    "Dordi Khola Jal Bidyut Company Limited": "Hydro Power",
    "Eastern Hydropower Limited": "Hydro Power",
    "Emerging Nepal Limited": "Hydro Power",
    "First Micro Finance Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Forward Microfinance Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Garima Debenture, 2085": "Debenture",
    "Ghorahi Cement Industry Limited": "GCIL",
    "Global IME Balanced Fund-1": "GIBF1",
    "Greenlife Hydropower Limited": "Hydro Power",
    "Ganapati Microfinance Bittiya Sanstha Ltd": "Microfinance",
    "Green Ventures Limited": "GVL",
    "12% Goodwill finance Debenture 2083": "Debenture",
    "Himalayan 80-20": "H8020",
    "Hathway Investment Nepal Limited": "HATHY",
    "Himalayan Everest Insurance Limited": "Non Life Insurance",
    "Himalayan Everest Insurance Limited Promoter": "HEIP",
    "Himalayan Hydropower Limited": "Hydro Power",
    "Hydroelectricity Investment and Development Company Limited Promoter Share":
        "HIDCLP",
    "Himalayan Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Himalayan Life Insurance Limited": "HLI",
    "Himalayan Reinsurance Limited": "HRL",
    "IGI Prudential Insurance Company Limited": "IGI",
    "Ingwa Hydropower Limited": "Hydro Power",
    "IME Life Insurance Company Limited": "ILI",
    "Jalpa Samudayik Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Jeevan Bikas Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Janautthan Samudayic Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "10.25% Kumari Bank Debenture 2086": "Debenture",
    "Kutheli Bukhari Small Hydropower Limited": "Hydro Power",
    "Kumari Dhanabriddhi Yojana": "KDBY",
    "Kalinchowk Darshan Limited": "Hotels",
    "Kalika Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "9% Kamana Sewa Bikas Bank Limited Debenture 2087": "Debenture",
    "11% L.B.B.L. Debenture 2089": "Debenture",
    "Laxmi Sunrise Bank Limited": "LSL",
    "Laxmi unnati Kosh": "LUK",
    "Makar Jitumaya Suri Hydropower Limited": "Hydro Power",
    "Mandu Hydropower Ltd.": "Hydro Power",
    "Madhya Bhotekoshi Jalavidyut Company Limited": "MBJC",
    "Machhapuchchhre Bank Limited": "MBL",
    "Menchhiyam Hydropower Limited": "Hydro Power",
    "Manakamana Engineering Hydropower Limited": "Hydro Power",
    "Modi Energy Limited": "Hydro Power",
    "Meromicrofinance Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Molung Hydropower Company Limited": "Hydro Power",
    "Mandakini Hydropower Limited": "Hydro Power",
    "Muktinath Krishi Company Limited": "Hydro Power",
    "Maya Khola Hydropower Company Limited": "Hydro Power",
    "Mai Khola Hydropower Limited": "Hydro Power",
    "Mailung Khola Jal Vidhyut Company  Limited": "Hydro Power",
    "Manakamana Smart Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Mithila Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Manushi Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Mahila Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Mega Mutual Fund-1": "MMF1",
    "Mathillo Mailun Khola Jalvidhyut Limited": "MMKJL",
    "Mid-Solu Hydropower Limited": "Hydro Power",
    "Mahuli Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Nadep Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "nabil Balanced Fund-3": "NBF3",
    "8% Nabil Debenture 2085": "Debenture",
    "8.5% Nepal Bank Debenture 2087": "Debenture",
    "NESDO Sambridha Laghubitta Bittiye Sanstha Limited": "Microfinance",
    "10.5% Nepal Investment Debenture 2082": "Debenture",
    "NIBL Growth Fund": "NIBLGF",
    "NIBL Samriddhi Fund 2": "NIBSF2",
    "NIC ASIA Flexi CAP Fund": "NICFC",
    "NIC Asia Growth Fund-2": "NICGF2",
    "NIC Asia Laghubitta Biitiya Sanstha Limited": "NICLBSL",
    "NIC Asia Select - 30 ": "NICSF",
    "Nifra Urja 7% -2085/86": "NIFRAUR85/86",
    "Nepal Investment Mega Bank Limited ": "Commercial Banks",
    "10% NIMB Debenture 2090": "Debenture",
    "Nepal Investment Mega Bank Ltd. Promoter Share ": "NIMBPO",
    "8.50% NMB Rinpatra 2087/88": "NMBD87/88",
    "NMB Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "National Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Nepal Re-Insurance Company Limited": "Non Life Insurance",
    "Nepal Republic Media Limited": "NRM",
    "NMB Sulav Investment Fund - 2": "NSIF2",
    "Nepal Warehousing Company Limited": "NWCL",
    "Nyadi Hydropower Limited": "Hydro Power",
    "Oriental Hotels Limited": "Hotels",
    "10% Prime Debenture 2088": "Debenture",
    "10% Prabhu Bank Debenture 2084 ": "Debenture",
    "8.5% Prabhu Bank Debenture 2087": "Debenture",
    "Peoples Hydropower Company Limited": "Hydro Power",
    "Prabhu Mahalaxmi Life Insurance Limited": "PMLI",
    "Panchthar Power Company Limited": "Hydro Power",
    "People": "PPL",
    "Progressive Finance Limited": "PROFL",
    "Prabhu Smart Fund": "PRSF",
    "Prabhu Bank Limited Promoter Share": "PRVUPO",
    "Prabhu Select Fund": "PSF",
    "Rawa Energy Development Limited": "Hydro Power",
    "8.5% RBBL Debenture 2083": "Debenture",
    "Rastriya Beema Company Limited Promoter Share": "Non Life Insurance",
    "River Falls Power Limited": "Hydro Power",
    "Rapti Hydro and General Construction Limited": "Hydro Power",
    "Ridi Power Company Limited": "Hydro Power",
    "RBB Mutual Fund 1": "RMF1",
    "RBB Mutual Fund 2": "RMF2",
    "Reliable Nepal Life Insurance Limited": "Life Insurance",
    "Sanima Growth Fund": "SAGF",
    "Sahas Urja Limited": "Hydro Power",
    "Sagarmatha Lumbini Insurance Co. Limited": "Non Life Insurance",
    "Samaj Laghubittya Bittiya Sanstha Limited": "Microfinance",
    "Sarbottam Cement Limited": "Manufacturing And Processing",
    "9% Shangri-la Development Bank Debenture 2087": "Debenture",
    "Sunrise Focused Equity Fund": "SFEF",
    "Swet-Ganga Hydropower & Construction Limited ": "Hydro Power",
    "Sanima GIC Insurance Limited": "SGIC",
    "Soaltee Hotel Limited": "Hotels",
    "Shrijanshil Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Siddhartha Investment Growth Scheme 3	": "SIGS3",
    "Sikles Hydropower Limited": "Hydro Power",
    "SuryaJyoti Life Insurance Company Limited": "Life Insurance",
    "Sana Kisan Bikas Laghubitta Bittiya sanstha Limited.": "Microfinance",
    "Swarojgar Laghubitta Bittiya Sanstha Ltd.": "Microfinance",
    "Swabhimaan Laghubitta Bittiya Sanstha Ltd": "Microfinance",
    "Super Mai Hydropower Limited": "Hydro Power",
    "Super Madi Hydropower Limited": "Hydro Power",
    "Sagarmatha Jalabidhyut Company Limited": "Hydro Power",
    "Sun Nepal Life Insurance Company Limited": "Life Insurance",
    "Sonapur Minerals and Oil Limited": "Manufacturing And Processing",
    "Samling Power Company Limited": "Hydro Power",
    "Sayapatri Hydropower Limited": "Hydro Power",
    "Siddhartha Premier Insurance Limited": "Non Life Insurance",
    "Shuvam Power Company Limited": "Hydro Power",
    "Sanima Reliance Life Insurance Limited": "Life Insurance",
    "Shiva Shree Hydropower Limited": "Hydro Power",
    "Suryodaya Womi Laghubitta Bittiya Sanstha Limited ": "Microfinance",
    "Sanima Middle Tamor Hydropower Limited": "Hydro Power",
    "Terhathum Power Company Limited": "Hydro Power",
    "Three Star Hydropower Limited": "Hydro Power",
    "Trishuli Jal Vidhyut Company Limited": "Hydro Power",
    "United Ajod Insurance Limited ": "Non Life Insurance",
    "Upper Hewakhola Hydropower Company Limited": "Hydro Power",
    "Upakar Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Upper Lohore Khola Hydropower Company Limited": "Hydro Power",
    "Unique Nepal Laghubitta Bittiya Sanstha Limited": "Microfinance",
    "Upper Solu Hydro Electric Company Limited ": "Hydro Power",
    "Upper Syange  Hydropower Limited": "Hydro Power",
    "Vision Lumbini Urja Company Limited": "Hydro Power",
    "WEAN Nepal Laghubitta Bittiya Sanstha Limited": "Microfinance",
  };
}
